CREATE TABLE [CQC].[active_locations_staging] (
    [Location ID]                                                                                                                    VARCHAR (255) NULL,
    [Location HSCA start date]                                                                                                       VARCHAR (255) NULL,
    [Dormant (Y/N)]                                                                                                                  VARCHAR (255) NULL,
    [Care home?]                                                                                                                     VARCHAR (255) NULL,
    [Location Name]                                                                                                                  VARCHAR (255) NULL,
    [Location ODS Code]                                                                                                              VARCHAR (255) NULL,
    [Location Telephone Number]                                                                                                      VARCHAR (255) NULL,
    [Registered manager]                                                                                                             VARCHAR (255) NULL,
    [Location Web Address]                                                                                                           VARCHAR (255) NULL,
    [Care homes beds]                                                                                                                VARCHAR (255) NULL,
    [Location Type/Sector]                                                                                                           VARCHAR (255) NULL,
    [Location Inspection Directorate]                                                                                                VARCHAR (255) NULL,
    [Location Primary Inspection Category]                                                                                           VARCHAR (255) NULL,
    [Location Latest Overall Rating]                                                                                                 VARCHAR (255) NULL,
    [Publication Date]                                                                                                               VARCHAR (255) NULL,
    [Inherited Rating (Y/N)]                                                                                                         VARCHAR (255) NULL,
    [Location Region]                                                                                                                VARCHAR (255) NULL,
    [Location NHS Region]                                                                                                            VARCHAR (255) NULL,
    [Location Local Authority]                                                                                                       VARCHAR (255) NULL,
    [Location ONSPD CCG Code]                                                                                                        VARCHAR (255) NULL,
    [Location ONSPD CCG]                                                                                                             VARCHAR (255) NULL,
    [Location Commissioning CCG Code]                                                                                                VARCHAR (255) NULL,
    [Location Commissioning CCG]                                                                                                     VARCHAR (255) NULL,
    [Location Street Address]                                                                                                        VARCHAR (255) NULL,
    [Location Address Line 2]                                                                                                        VARCHAR (255) NULL,
    [Location City]                                                                                                                  VARCHAR (255) NULL,
    [Location County]                                                                                                                VARCHAR (255) NULL,
    [Location Postal Code]                                                                                                           VARCHAR (255) NULL,
    [Location PAF ID]                                                                                                                VARCHAR (255) NULL,
    [Location UPRN ID]                                                                                                               VARCHAR (255) NULL,
    [Location Latitude]                                                                                                              VARCHAR (255) NULL,
    [Location Longitude]                                                                                                             VARCHAR (255) NULL,
    [Location Parliamentary Constituency]                                                                                            VARCHAR (255) NULL,
    [Brand ID]                                                                                                                       VARCHAR (255) NULL,
    [Brand Name]                                                                                                                     VARCHAR (255) NULL,
    [Provider Companies House Number]                                                                                                VARCHAR (255) NULL,
    [Provider Charity Number]                                                                                                        VARCHAR (255) NULL,
    [Provider ID]                                                                                                                    VARCHAR (255) NULL,
    [Provider Name]                                                                                                                  VARCHAR (255) NULL,
    [Provider HSCA start date]                                                                                                       VARCHAR (255) NULL,
    [Provider Type/Sector]                                                                                                           VARCHAR (255) NULL,
    [Provider Inspection Directorate]                                                                                                VARCHAR (255) NULL,
    [Provider Primary Inspection Category]                                                                                           VARCHAR (255) NULL,
    [Provider Ownership Type]                                                                                                        VARCHAR (255) NULL,
    [Provider Telephone Number]                                                                                                      VARCHAR (255) NULL,
    [Provider Web Address]                                                                                                           VARCHAR (255) NULL,
    [Provider Street Address]                                                                                                        VARCHAR (255) NULL,
    [Provider Address Line 2]                                                                                                        VARCHAR (255) NULL,
    [Provider City]                                                                                                                  VARCHAR (255) NULL,
    [Provider County]                                                                                                                VARCHAR (255) NULL,
    [Provider Postal Code]                                                                                                           VARCHAR (255) NULL,
    [Provider PAF ID]                                                                                                                VARCHAR (255) NULL,
    [Provider UPRN ID]                                                                                                               VARCHAR (255) NULL,
    [Provider Local Authority]                                                                                                       VARCHAR (255) NULL,
    [Provider Region]                                                                                                                VARCHAR (255) NULL,
    [Provider NHS Region]                                                                                                            VARCHAR (255) NULL,
    [Provider Latitude]                                                                                                              VARCHAR (255) NULL,
    [Provider Longitude]                                                                                                             VARCHAR (255) NULL,
    [Provider Parliamentary Constituency]                                                                                            VARCHAR (255) NULL,
    [Provider Nominated Individual Name]                                                                                             VARCHAR (255) NULL,
    [Provider Main Partner Name]                                                                                                     VARCHAR (255) NULL,
    [Regulated activity - Accommodation for persons who require nursing or personal care]                                            VARCHAR (255) NULL,
    [Regulated activity - Accommodation for persons who require treatment for substance misuse]                                      VARCHAR (255) NULL,
    [Regulated activity - Assessment or medical treatment for persons detained under the Mental Health Act 1983]                     VARCHAR (255) NULL,
    [Regulated activity - Diagnostic and screening procedures]                                                                       VARCHAR (255) NULL,
    [Regulated activity - Family planning]                                                                                           VARCHAR (255) NULL,
    [Regulated activity - Management of supply of blood and blood derived products]                                                  VARCHAR (255) NULL,
    [Regulated activity - Maternity and midwifery services]                                                                          VARCHAR (255) NULL,
    [Regulated activity - Nursing care]                                                                                              VARCHAR (255) NULL,
    [Regulated activity - Personal care]                                                                                             VARCHAR (255) NULL,
    [Regulated activity - Services in slimming clinics]                                                                              VARCHAR (255) NULL,
    [Regulated activity - Surgical procedures]                                                                                       VARCHAR (255) NULL,
    [Regulated activity - Termination of pregnancies]                                                                                VARCHAR (255) NULL,
    [Regulated activity - Transport services, triage and medical advice provided remotely]                                           VARCHAR (255) NULL,
    [Regulated activity - Treatment of disease, disorder or injury]                                                                  VARCHAR (255) NULL,
    [Service type - Acute services with overnight beds]                                                                              VARCHAR (255) NULL,
    [Service type - Acute services without overnight beds / listed acute services with or without overnight beds]                    VARCHAR (255) NULL,
    [Service type - Ambulance service]                                                                                               VARCHAR (255) NULL,
    [Service type - Blood and Transplant service]                                                                                    VARCHAR (255) NULL,
    [Service type - Care home service with nursing]                                                                                  VARCHAR (255) NULL,
    [Service type - Care home service without nursing]                                                                               VARCHAR (255) NULL,
    [Service type - Community based services for people who misuse substances]                                                       VARCHAR (255) NULL,
    [Service type - Community based services for people with a learning disability]                                                  VARCHAR (255) NULL,
    [Service type - Community based services for people with mental health needs]                                                    VARCHAR (255) NULL,
    [Service type - Community health care services - Nurses Agency only]                                                             VARCHAR (255) NULL,
    [Service type - Community healthcare service]                                                                                    VARCHAR (255) NULL,
    [Service type - Dental service]                                                                                                  VARCHAR (255) NULL,
    [Service type - Diagnostic and/or screening service]                                                                             VARCHAR (255) NULL,
    [Service type - Diagnostic and/or screening service - single handed sessional providers]                                         VARCHAR (255) NULL,
    [Service type - Doctors consultation service]                                                                                    VARCHAR (255) NULL,
    [Service type - Doctors treatment service]                                                                                       VARCHAR (255) NULL,
    [Service type - Domiciliary care service]                                                                                        VARCHAR (255) NULL,
    [Service type - Extra Care housing services]                                                                                     VARCHAR (255) NULL,
    [Service type - Hospice services]                                                                                                VARCHAR (255) NULL,
    [Service type - Hospice services at home]                                                                                        VARCHAR (255) NULL,
    [Service type - Hospital services for people with mental health needs, learning disabilities and problems with substance misuse] VARCHAR (255) NULL,
    [Service type - Hyperbaric Chamber]                                                                                              VARCHAR (255) NULL,
    [Service type - Long term conditions services]                                                                                   VARCHAR (255) NULL,
    [Service type - Mobile doctors service]                                                                                          VARCHAR (255) NULL,
    [Service type - Prison Healthcare Services]                                                                                      VARCHAR (255) NULL,
    [Service type - Rehabilitation services]                                                                                         VARCHAR (255) NULL,
    [Service type - Remote clinical advice service]                                                                                  VARCHAR (255) NULL,
    [Service type - Residential substance misuse treatment and/or rehabilitation service]                                            VARCHAR (255) NULL,
    [Service type - Shared Lives]                                                                                                    VARCHAR (255) NULL,
    [Service type - Specialist college service]                                                                                      VARCHAR (255) NULL,
    [Service type - Supported living service]                                                                                        VARCHAR (255) NULL,
    [Service type - Urgent care services]                                                                                            VARCHAR (255) NULL,
    [Service user band - Children 0-18 years]                                                                                        VARCHAR (255) NULL,
    [Service user band - Dementia]                                                                                                   VARCHAR (255) NULL,
    [Service user band - Learning disabilities or autistic spectrum disorder]                                                        VARCHAR (255) NULL,
    [Service user band - Mental Health]                                                                                              VARCHAR (255) NULL,
    [Service user band - Older People]                                                                                               VARCHAR (255) NULL,
    [Service user band - People detained under the Mental Health Act]                                                                VARCHAR (255) NULL,
    [Service user band - People who misuse drugs and alcohol]                                                                        VARCHAR (255) NULL,
    [Service user band - People with an eating disorder]                                                                             VARCHAR (255) NULL,
    [Service user band - Physical Disability]                                                                                        VARCHAR (255) NULL,
    [Service user band - Sensory Impairment]                                                                                         VARCHAR (255) NULL,
    [Service user band - Whole Population]                                                                                           VARCHAR (255) NULL,
    [Service user band - Younger Adults]                                                                                             VARCHAR (255) NULL
);
GO

