CREATE TABLE [CQC].[latest_ratings_locations_staging] (
    [Location ID]                          VARCHAR (255) NULL,
    [Location ODS Code]                    VARCHAR (255) NULL,
    [Location Name]                        VARCHAR (255) NULL,
    [Care Home?]                           VARCHAR (255) NULL,
    [Location Type]                        VARCHAR (255) NULL,
    [Location Primary Inspection Category] VARCHAR (255) NULL,
    [Location Street Address]              VARCHAR (255) NULL,
    [Location Address Line 2]              VARCHAR (255) NULL,
    [Location City]                        VARCHAR (255) NULL,
    [Location Post Code]                   VARCHAR (255) NULL,
    [Location Local Authority]             VARCHAR (255) NULL,
    [Location Region]                      VARCHAR (255) NULL,
    [Location NHS Region]                  VARCHAR (255) NULL,
    [Location ONSPD CCG Code]              VARCHAR (255) NULL,
    [Location ONSPD CCG]                   VARCHAR (255) NULL,
    [Location Commissioning CCG Code]      VARCHAR (255) NULL,
    [Location Commissioning CCG Name]      VARCHAR (255) NULL,
    [Service / Population Group]           VARCHAR (255) NULL,
    [Domain]                               VARCHAR (255) NULL,
    [Latest Rating]                        VARCHAR (255) NULL,
    [Publication Date]                     VARCHAR (255) NULL,
    [Report Type]                          VARCHAR (255) NULL,
    [Inherited Rating (Y/N)]               VARCHAR (255) NULL,
    [URL]                                  VARCHAR (255) NULL,
    [Provider ID]                          VARCHAR (255) NULL,
    [Provider Name]                        VARCHAR (255) NULL,
    [Brand ID]                             VARCHAR (255) NULL,
    [Brand Name]                           VARCHAR (255) NULL
);
GO

